import Head from "next/head";
import { Amaranth } from "next/font/google";
import { Box, ThemeProvider, createTheme } from "@mui/material";
import { AnimatePresence, } from "framer-motion";
import BodyController from "@/components/bodyScroller";

const inter = Amaranth({ subsets: ["latin"], weight: "400" });

export default function Home() {

  const theme = createTheme({
    typography: {
      allVariants: {
        fontFamily: "Amaranth",
      }
    },
    components: {
      MuiChip: {
        styleOverrides: {
          label: {
            fontFamily: "Amaranth",
          }
        }
      }
    }
  });

  return (
    <>
      <Head>
        <title>Ignacio Romanow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Amaranth:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={` ${inter.className}`} style={{ scrollBehavior: 'smooth' }}>
        <AnimatePresence>
          <ThemeProvider theme={theme}>
            <Box>
              <BodyController />
            </Box>
          </ThemeProvider>
        </AnimatePresence>
      </main >
    </>
  );
}
